export const LOAD_RECIPES_SUCCESS = 'LOAD_RECIPES_SUCCESS';

export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE_FAILURE = 'CREATE_RECIPE_FAILURE';

export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_FAILURE = 'UPDATE_RECIPE_FAILURE';

export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_FAILURE = 'DELETE_RECIPE_FAILURE';

export const BEGIN_ASYNCCALL = 'BEGIN_ASYNCCALL';

export const UPDATE_CURRENTRECIPE = 'UPDATE_CURRENTRECIPE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
