export const LOAD_RECIPES_SUCCESS = 'LOAD_RECIPES_SUCCESS';

export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE_FAILURE = 'CREATE_RECIPE_FAILURE';

export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_FAILURE = 'UPDATE_RECIPE_FAILURE';

export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_FAILURE = 'DELETE_RECIPE_FAILURE';

export const LOAD_SEARCH_EXTERNAL_RECIPES_SUCCESS = 'LOAD_SEARCH_EXTERNAL_RECIPES_SUCCESS';

export const BEGIN_ASYNCCALL = 'BEGIN_ASYNCCALL';

export const UPDATE_CURRENTRECIPE = 'UPDATE_CURRENTRECIPE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERR = 'AUTH_ERR';
export const GET_USER = 'GET_USER';

export const API_URL = process.env.REACT_APP_APIURL || "http://localhost:3001";
export const CLIENT_URL = process.env.REACT_APP_CLIENTURL || "http://localhost:3000";

